config/routes.rb
Rails.application.routes.draw do
  # get 'sessions/new'

  namespace :admin do
    resources :products
    resources :users
    resources :transactions
    resources :charges

  end
  get 'admin', to: 'admin#control_panel'
# post '/cart_items/:product_id' => 'cart_items#create', :as => 'add_to_cart'
post '/add_to_cart/:product_id' => 'cart#add_product', :as => 'add_to_cart'

  # get 'sessions/create'
  get '/login' => 'sessions#new'
  post "/login", to: "sessions#create", as: "signin"
  post '/logout' => 'sessions#destroy'
  get '/logout' => 'sessions#destroy'
  get  '/hello' => 'sessions#hello'
  get '/signup' => 'users#new'
  resources :cart
  resources :cart_items
   # get "cart_items/create"
  resources :charges
  resources :transactions, only: [:new, :show]
  resources :users, only: [:new, :show, :edit, :create]
  resources :products, only: [:index, :show]
  root 'application#index'
  get 'thanks', to: 'charges#thanks', as: 'thanks'
  # root 'application#hello'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/user.rb
class User < ApplicationRecord
	validates :password, confirmation: true
	validates :first_name, presence: true, format: { without: /[0-9]/, message: "does not allow numbers" }
	validates :last_name, presence: true, format: { without: /[0-9]/, message: "does not allow numbers" }
	validates :email,
            presence: true,
            uniqueness: true,
            format: {
              with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i
            }
	validates :password, length: { in: 6..20 }
    
    has_secure_password
    has_many :cart_items
     has_many :carts

   def to_s
    "#{first_name} #{last_name}"
  end

  def gather_transactions
  	# create a list of a specific user's transactions to print to the view
  	User.transactions
  end
  def transations_count
  	self.transactions.count
  end
end

app/controllers/admin/users_controller.rb
class Admin::UsersController < ApplicationController
  before_action :must_be_admin, only: [:edit, :update, :destroy]
  # before_action :require_login
  # skip_before_action :require_login, only: [:index, :new]
   before_action :set_user, only: [:show, :edit, :update, :destroy]
  # skip_before_action :require_login, only: [:index, :new]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    # set_user
    if @user.transactions
      @transactions = @user.transactions
      # display transactions
    else
      # display "Hey, you don't have any transactions yet!"
    end


    # IN VIEW
    # <% if @transactions %>
    #   <% @transactions.each do |t| %>
    #     <%= t.id %>
    #     <%= t.price %>
    #   <% end %>
    # <% end %>
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    # set_user
  end

  # POST /users
  # POST /users.json
  def create
    # set_user

    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to admin_users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def require_login
    return head(:forbidden) unless session.include? :user_id    
  end

    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :is_admin )
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
 
	 before_action :set_user, only: [:show, :edit, :update, :destroy]
  # skip_before_action :current_user, only: [:index, :new]
  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
    # set_user
    if @user.charges
      @charges = @user.charges
      # display transactions
    else
      # display "Hey, you don't have any transactions yet!"
    end


    # IN VIEW
    # <% if @transactions %>
    #   <% @transactions.each do |t| %>
    #     <%= t.id %>
    #     <%= t.price %>
    #   <% end %>
    # <% end %>
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
    # set_user
  end

  # POST /users
  # POST /users.json
  def create
    # set_user

    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        log_in @user
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render :show, status: :created, location: @user }
      else
        format.html { render :new }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { render :show, status: :ok, location: @user }
      else
        format.html { render :edit }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to adnin_users_url, notice: 'User was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def require_login
    return head(:forbidden) unless session.include? :user_id    
  end

    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:first_name, :last_name, :email, :password, :password_confirmation, :is_admin )
    end
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

<div class="wrapper form">
  <div class="field">
    <%= f.label :first_name %>
    <%= f.text_field :first_name %>
  </div>

  <div class="field">
    <%= f.label :last_name %>
    <%= f.text_field :last_name %>
  </div>

  <div class="field">
    <%= f.label :email %>
    <%= f.text_field :email %>
  </div>

  <div class="field">
    <%= f.label :password %>
    <%= f.password_field :password %>
  </div>

  <div class="field">
  Password Confirmation: <%= f.password_field :password_confirmation %>
  </div>
  
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>

app/views/users/edit.html.erb
<h1>Editing User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Users</h1>
<div class="wrapper">
<table>
  <thead>
    <tr>
      <th>First name</th>
      <th>Last name</th>
      <th>Email</th>
      <th>Password</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.first_name %></td>
        <td><%= user.last_name %></td>
        <td><%= user.email %></td>
        <td><%= user.password %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>
</div>
<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New User</h1>

<%= render 'form', user: @user %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<div class="wrapper form">
	

	<p id="notice"><%= notice %></p>

	<p>
		<strong>First name:</strong>
		<%= @user.first_name %>
	</p>

	<p>
		<strong>Last name:</strong>
		<%= @user.last_name %>
	</p>

	<p>
		<strong>Email:</strong>
		<%= @user.email %>
	</p>

	<p>
		<strong>Password:</strong>
		<%= @user.password %>
	</p>
	<p>
		<strong>
			<% if @user.charges.count == 0 %>
			<%= "You have no transactions" %> <br>
			
			<%else%>
			<h3><%= pluralize(@user.charges.count, 'Transaction') %></h3>
			<ul>
				<% @user.charges.each do |trans| %>
				<li><%= link_to trans.product.name, product_path(trans) %></li>
				<% end %>
				<%end%>
			</ul>
			<% if current_user %>
Logged in as <%= current_user.first_name %>
<% else %>

			<%= link_to 'Log in', signin_path %>
			<%end%>

		</strong>
	</p>
	
</div>


<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Home', root_path %>