config/routes.rb
Rails.application.routes.draw do
  # get 'sessions/new'

  namespace :admin do
    resources :products
    resources :users
    resources :transactions
    resources :charges

  end
  get 'admin', to: 'admin#control_panel'
# post '/cart_items/:product_id' => 'cart_items#create', :as => 'add_to_cart'
post '/add_to_cart/:product_id' => 'cart#add_product', :as => 'add_to_cart'

  # get 'sessions/create'
  get '/login' => 'sessions#new'
  post "/login", to: "sessions#create", as: "signin"
  post '/logout' => 'sessions#destroy'
  get '/logout' => 'sessions#destroy'
  get  '/hello' => 'sessions#hello'
  get '/signup' => 'users#new'
  resources :cart
  resources :cart_items
   # get "cart_items/create"
  resources :charges
  resources :transactions, only: [:new, :show]
  resources :users, only: [:new, :show, :edit, :create]
  resources :products, only: [:index, :show]
  root 'application#index'
  get 'thanks', to: 'charges#thanks', as: 'thanks'
  # root 'application#hello'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/product.rb
class Product < ApplicationRecord
	has_many :charges
	has_many :cart_items
  has_many :carts, :through => :cart_items
end

app/controllers/admin/products_controller.rb
class Admin::ProductsController < ApplicationController
  before_action :must_be_admin, only: [:edit, :update, :destroy]
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

# def thanks
#   @product=Product.new(params[:price])
#   end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to admin_products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
   #Use callbacks to share common setup or constraints between actions.
   def set_product
     @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :size, :imageURL, :description, :transaction_id)
    end
end

app/controllers/products_controller.rb
class ProductsController < ApplicationController
   before_action :logged_in_user
  before_action :set_product, only: [:show, :edit, :update, :destroy]

  # GET /products
  # GET /products.json
  def index
    @products = Product.all
     @cart_item = @cart.cart_items.new
  end

  # GET /products/1
  # GET /products/1.json
  def show
  end

  # GET /products/new
  def new
    @product = Product.new
  end

  # GET /products/1/edit
  def edit
  end

# def thanks
#   @product=Product.new(params[:price])
#   end

  # POST /products
  # POST /products.json
  def create
    @product = Product.new(product_params)

    respond_to do |format|
      if @product.save
        format.html { redirect_to @product, notice: 'Product was successfully created.' }
        format.json { render :show, status: :created, location: @product }
      else
        format.html { render :new }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /products/1
  # PATCH/PUT /products/1.json
  def update
    respond_to do |format|
      if @product.update(product_params)
        format.html { redirect_to @product, notice: 'Product was successfully updated.' }
        format.json { render :show, status: :ok, location: @product }
      else
        format.html { render :edit }
        format.json { render json: @product.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /products/1
  # DELETE /products/1.json
  def destroy
    @product.destroy
    respond_to do |format|
      format.html { redirect_to admin_products_url, notice: 'Product was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
   #Use callbacks to share common setup or constraints between actions.
   def set_product
     @product = Product.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def product_params
      params.require(:product).permit(:name, :price, :size, :imageURL, :description, :transaction_id)
    end
end

app/helpers/products_helper.rb
module ProductsHelper
end

app/views/products/_form.html.erb
<%= form_for(@product) do |f| %>
  <% if @product.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@product.errors.count, "error") %> prohibited this product from being saved:</h2>

      <ul>
      <% @product.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>
<div class="wrapper form">
  <div class="field">
    <%= f.label :name %>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :imageURL %>
    <%= f.text_field :imageURL %>
  </div>

  <div class="field">
    <%= f.label :price %>
    <%= f.text_field :price %>$
  </div>

  <div class="field">
    <%= f.label :size %>
    <%= f.number_field :size %>
  </div>

  <div class="field">
  <%= f.label :description %>
    <%= f.text_area :description, size: "60x10" %>
  </div>

  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>
</div>
<button type="button">
<%= link_to 'buy Now', new_charge_path %></button>

app/views/products/edit.html.erb
<h1>Editing Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Show', @product %> |
<%= link_to 'Back', products_path %>

app/views/products/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Products</h1>
<div class="wrapper">

    <% @products.each do |product| %>
    <section id="promotional" class="col-1 first shadow">
          <figure>
    <%= image_tag("#{product.imageURL}", :alt => "Product Image",:class => "img-product") %>
    </figure>
      <h3><%= product.name %></h3>
      <h3><%= product.price %>$</h3>
      <h4><%= product.size %></h4>
       <td><%= link_to 'see more', product_path(product) %></td>
        <td><%= button_to "Add to Cart", cart_items_path(:product_id => product, :cart_id => @cart ), :method => :post, :class => "button" %></td>
     </section>
    <% end %>
  
</div>
<br>

app/views/products/new.html.erb
<h1>New Product</h1>

<%= render 'form', product: @product %>

<%= link_to 'Back', products_path %>

app/views/products/show.html.erb
<div class="wrapper form">

<p id="notice"><%= notice %></p>
<figure>
<%= image_tag(@product.imageURL, :alt => "Product Image",:class => "img-product") %>
	</figure>

<p>
  <strong>Name:</strong>
  <%= @product.name %>
</p>

<p>
  <strong>Price:</strong>
  <%= @product.price %>
</p>

<p>
  <strong>Size:</strong>
  <%= @product.size %>
</p>

<p>
  <strong>description:</strong>
  <%= @product.description %>
</p>
<%= form_tag charges_path do %>
  <article>
    <% if flash[:error].present? %>
      <div id="error_explanation">
        <p><%= flash[:error] %></p>
      </div>
    <% end %>
    <label class="amount">
      <span>Amount:<%=@product.price%></span>
    </label>
    <%= hidden_field_tag 'id', params[:id] %>
    
  </article>

  <script src="https://checkout.stripe.com/checkout.js" class="stripe-button"
          data-key="<%= Rails.configuration.stripe[:publishable_key] %>"
          data-description="<%=@product.id%>"
          data-amount="<%=@product.price * 100%>"
          data-locale="auto"></script>
<% end %>

 


<%= link_to 'Back', admin_products_path %>